version: '2'

services:

  apache-server:
    build:
      context: ./docker/apache
    #image: apps4net/vue-apache:1.4
#    image: apache
    ports:
      - ${APP_PORT}
#      - "443:443"
    restart: always
    volumes:
      - ./www:/var/www/html
