version: '2'

services:

  apache-server:
    image: apps4net/vue-apache:1.0
#    image: apache
    ports:
      - ${APP_PORT}
#      - "443:443"
    restart: always
    volumes:
      - ./www:/var/www/html